export default class KeyInformation {
  agoraInfo = {
    //AppID: 'ffe4548efb124f36b8827362125334f1',
    //AppCertificate: 'ed541556e16c47e5ac39624e4a9c5177',
    //ChannelName: '', //Token,ChannelName should be generated by users daily
    //Token,ChannelName: default for 24 hours defined by Agora
    //Token:'007eJxTYDjnXv989VvBr7NO3Lj+qNJtrVHcog9rDmb1Fl/cfYR9eutyBYa0tFQTUxOL1LQkQyOTNGOzJAsLI3NjMyNDI1NjY5M0QzFNrZSGQEaGo6kmLIwMEAji8zH4VrplFhWXOGck5uWl5jAwAADRbiVw',
    //ApiKey: '79d173a86bb1451fafd895e87df9b727',
    //ApiSecert: '767b650716e74b859e81e3e981061623',
  };

  //return agoraInfo;
}
